version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env


volumes:
  postgres_data:
